name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Semantic Version Number (i.e., 5.5.0 or patch, minor, major, prerelease)'
        required: true
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Change version number and name
      run: npm version ${{ github.event.inputs.versionName }}
    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.1.1
    - name: Create release branch
      run: git checkout -b release/v${{ steps.extract_version.outputs.version }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add package.json
        git commit --message "release ${{ steps.extract_version.outputs.version }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/v${{ steps.extract_version.outputs.version }}
    - name: Create pull request into main
      uses: peter-evans/create-pull-request@v3
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ steps.extract_version.outputs.version }}
       base: main
       title: Release v${{ steps.extract_version.outputs.version }}
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
    # - name: Create pull request to develop
    #   uses: thomaseizinger/create-pull-request@1.0.0
    #   with:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       head: release/v${{ github.event.inputs.versionName }}
    #       base: develop
    #       title: v${{ github.event.inputs.versionName }} into develop
    #       reviewers: ${{ github.event.issue.user.login }}
    #       body: |
    #           Hi!
    #           This PR was created in response workflow running.
    #           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.