name: Create Release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Semantic Version Number (i.e., 5.5.0 or patch, minor, major, prerelease)'
        required: true
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Change version number
      run: npm version --no-git-tag-version ${{ github.event.inputs.versionName }}
    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.1.1
    - name: Create release branch
      run: git checkout -b release/v${{ steps.extract_version.outputs.version }}
    - name: Create pull request into main
      uses: peter-evans/create-pull-request@v3
      with:
        branch: release/v${{ steps.extract_version.outputs.version }}
        commit-message: "chore: release v${{ steps.extract_version.outputs.version }}"
        base: main
        title: Release v${{ steps.extract_version.outputs.version }}
        reviewers: ${{ github.event.issue.user.login }}
        labels: chore
        body: |
            Releasing v${{ steps.extract_version.outputs.version }}.
